### ISSUE TITLE
PythonBridgeOptions not compatible with Node.js

### ISSUE THREAD

**Issue by zixia** [Submersible/node-python-bridge#17]
According to the Node.js types:

```ts
    export interface ProcessEnv {
      [key: string]: string | undefined
    }
```

We need to compatible with it by:

```diff
-  env?: { [key:string]: string; };
+  env?: { [key: string]: string | undefined; };
```

**Comment by zixia** [comment]
Ah, you are so fast!

Please update npm. :+1:

**Comment by munro** [comment]
heh I'm at the computer, also nobody got time for test build

**Comment by zixia** [comment]
Bravo! I'm using the new npm now.

**Comment by zixia** [comment]
Thanks for inviting me for collaborating in this project.

What I'm doing now is to use python-bridge to integrate Node.js with Tensorflow in Python, the project name is **FaceNet**, it's a FaceNet Node.js Module for easy face recognition, verification, and clustering. See more at <https://github.com/zixia/facenet> . 

It seems work like a charm, so I will use it and try to contribute more in the future.

Thank you for the awesome project again!

**Comment by munro** [comment]
Awesome 😱   I've been wanting to play with tensorflow, I've been building some models with with `sklearn`.  I've also distributing computation computation with PySpark, which is a ton of fun when you have 12 nodes crushing 100s of GiBs of data in seconds!

IntelliJ has a feature that let's you inject syntax highlighting for embedded languages—you may be able to pull it off with your IDE as well!  It's not perfect though.. also sorry, I had to add `;` because it was visually yelling at me lol

![image](https://user-images.githubusercontent.com/500774/28851440-52c55c4a-76d7-11e7-8e63-c76fc5c874ab.png)

**Comment by zixia** [comment]
Great to hear that you are also interested in Tensorflow!

I'm using vscode because it has the best support for TypeScript, so I also use vscode as my Python IDE, it seems good enough for me now.

It seems you are already playing with facenet now, how do you think my project, do you think this kind of encapsulates will be useful?

I once have an idea that builds a `tensorflow-bridge`, that just bridge all the Python Tensorflow APIs to Node.js, use python bridge. 

P.S. there's two tensorflow binding for Node.js(as far as I know now):
1. <https://github.com/nodejs-tensorflow/nodejs-tensorflow>, @JIoJIaJIu start to support TypeScript after my suggestion.
1. <https://github.com/yorkie/tensorflow-nodejs> @yorkie seems not like the idea of TypeScript.
