### ISSUE TITLE
ModuleNotFound exceptions

### ISSUE THREAD

**Issue by gijswobben** [Submersible/node-python-bridge#25]
I'm trying to import a library from the working directory but I get a ModuleNotFound exception. I've been looking at the code and I think it might be related to this line: https://github.com/Submersible/node-python-bridge/blob/master/node_python_bridge.py#L91
Since there are no globals defined, the import system isn't working correctly. Is there a way to fix this?

```
let pythonBridge = require('python-bridge');

let python = pythonBridge({
    cwd: process.cwd()
});

python.ex`import mylibrary`;
python`x = mylibrary.helloWorld()`.then(x => {
    console.log(x)
});

python.end();
```

**Comment by munro** [comment]
@gijswobben Hmmmm, what you have should work—commands are queued up and ran in order (rules out that as a bug), and `globals()` state is shared between each command in the `_locals` dict.

From looking at your snippet, I think perhaps there may be a bug in `{cwd: process.cwd()}` not working as expected, what happens if you do `{env: {PYTHONPATH: process.cwd()}}`?

**Comment by munro** [comment]
@gijswobben Ohh I just tested your code, the issue is `x = ...` is a statement, and doesn't return a value, so you have to run it with `python.ex`—one day I'll release a version that tries to run it as an expression, and then automatically as a statement if that doesn't work.

Here's a working version of your code, `{cwd: process.cwd()}` worked as expected for me.

```javascript
let pythonBridge = require('./');

let python = pythonBridge({
    cwd: process.cwd()
});

python.ex`import mylibrary`;
python.ex`x = mylibrary.helloWorld()`;
python`x`.then(x => {
    console.log(x)
});

python.end();
```
