### ISSUE TITLE
Regex support using rfind()?

### ISSUE THREAD

**Issue by PSwan19** [Submersible/node-python-bridge#30]
When a value is '\n', I get "EOL while scanning string literal" while trying to use rfind(). Does Python-Bridge support regex in this manner? Apologies if this question is easily answered. I am new to JavaScript programming.

**Comment by munro** [comment]
@petuuuhhh Can you share a code snippet to reproduce the error?

**Comment by PSwan19** [comment]
Yes. `pos2 = max(setText.rfind(' (F) @ '),setText.rfind(' (F)  \n'))`

**Comment by munro** [comment]
<img width="857" alt="Screen Shot 2020-01-27 at 2 02 58 PM" src="https://user-images.githubusercontent.com/500774/73217938-c4c75700-410d-11ea-9d39-c2f6a277e3c4.png">

Oh yea I see what you mean, I just escaped the `\n` to become `\\n` and it worked.

It's interesting to thing to think about if that's desired, but this is the first time the issue has came up in 4 years so I'm inclined to leave it as is for now, but definitely open to changing if a case is made otherwise.  Changing it would break any current usage I believe, so I'm going to close for now.  But I'll definitely reopen if a case is made that a change makes the API more ergonomic!
